dataset/W3C/threads/Thread10001.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10011.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1002.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10021.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10022.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10027.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10028.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10034.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10038.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1004.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10040.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1005.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10052.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10058.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10065.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1007.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10082.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10090.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10093.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10096.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10097.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10110.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10114.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10127.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1014.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1015.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10150.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10157.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10169.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10179.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10181.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10190.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10206.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10207.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10213.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10220.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10227.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10235.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10238.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10240.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10248.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread1025.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10251.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10252.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10259.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10275.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10282.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10299.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10301.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10314.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10320.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10331.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10340.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10342.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10348.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10350.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10351.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10352.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10361.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10363.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10368.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10373.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10377.info.fragIDs.sent.parsed.ner
	dataset/W3C/threads/Thread10389.info.fragIDs.sent.parsed.ner
